# basic options
title: NBA-Calendar
author: Daniel Dantas Barreto
email: ddantas85@gmail.com
description: A wonderful site
twitter_username: sandey3
github_username:  ddantasds

# Build settings
markdown: kramdown
theme: minima
